# Site settings
title: garaemon.github.io
email: garaemon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  garaemon's blog. Talking about robotics and software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://garaemon.github.io" # the base hostname & protocol for your site
twitter_username: garaemon_coder
github_username:  garaemon

# Build settings
highlighter: rouge
markdown: kramdown
